branch-defaults:
  master:
    environment: ClassRoom-dev
    group_suffix: null
global:
  application_name: ClassRoom
  default_ec2_keyname: pankajd
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-cli
  sc: git
